guizi/urls.py
from django.conf.urls import include, url
from django.conf.urls.static import static
from django.contrib import admin
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
import core.management.urls as API_URL
import core.views as front
from guizi import settings

urlpatterns = [
    url(r'^admin/', include(admin.site.urls)),
    url(r'^management/', include(API_URL)),
    url(r'^user/', include('userena.urls')),
    url(r'^comments/', include('django_comments.urls')),
    url(r'^$', front.home, name="title"),
    url(r'^uploads/', front.uploads),
    url(r'^shop/$', front.shop),
    url(r'^shop/list/$', front.shop_list),
    # url(r'^shop/type/(?P<type_slug>[^/]+)/$', front.type),
    # url(r'^shop/brand/(?P<brand_slug>[^/]+)/$', front.brand),
    url(r'^shop/(?P<product_id>\d+)$', front.product_info),
    url(r'^portfolio/$', front.portfolio),
    url(r'^portfolio/(?P<portfolio_slug>[^/]+)/$', front.portfolio_info),
    url(r'^article/$', front.blog),
    url(r'^article/(?P<article_slug>[^/]+)/$', front.article_info),
    url(r'^activity/(?P<activity_slug>[^/]+)/$', front.activity_infor),
    url(r'like/', front.like),
    url(r'about-us/', front.aboutus, name="find-us"),
    url(r'find-us/', front.contact),
    url(r'^search/', include('haystack.urls')),
]

# Add media and static files
urlpatterns += staticfiles_urlpatterns()
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

profile/models.py
# -*- coding: utf-8 -*-

from django.db import models
from django.utils.translation import ugettext_lazy as _

from userena.models import UserenaLanguageBaseProfile
from userena.utils import user_model_label

import datetime


class Profile(UserenaLanguageBaseProfile):
    """ Default profile """
    GENDER_CHOICES = (
        (1, _('Male')),
        (2, _('Female')),
    )

    user = models.OneToOneField(user_model_label,
                                unique=True,
                                verbose_name=_('user'),
                                related_name='profile')

    gender = models.PositiveSmallIntegerField(_('gender'),
                                              choices=GENDER_CHOICES,
                                              blank=True,
                                              null=True)
    website = models.URLField(_('website'), blank=True)
    location =  models.CharField(_('location'), max_length=255, blank=True)
    birth_date = models.DateField(_('birth date'), blank=True, null=True)
    about_me = models.TextField(_('about me'), blank=True)

    @property
    def age(self):
        if not self.birth_date: return False
        else:
            today = datetime.date.today()
            # Raised when birth date is February 29 and the current year is not a
            # leap year.
            try:
                birthday = self.birth_date.replace(year=today.year)
            except ValueError:
                day = today.day - 1 if today.day != 1 else today.day + 2
                birthday = self.birth_date.replace(year=today.year, day=day)
            if birthday > today: return today.year - self.birth_date.year - 1
            else: return today.year - self.birth_date.year

    def __unicode__(self):
        return self.user.username

    class Meta:
        verbose_name = u'文章'
        verbose_name_plural = u'文章'

comment/forms.py
from django.contrib.contenttypes.models import ContentType
from django.forms import forms
from django.utils import timezone
from django.utils.encoding import force_text
from django.utils.text import get_text_list
from django.utils.translation import ungettext, ugettext
from django_comments.forms import CommentSecurityForm, COMMENT_MAX_LENGTH
from django_comments.models import Comment
from lightworks import settings

__author__ = 'whoisrex'


class CommentDetailsForm(CommentSecurityForm):
    """
    Handles the specific details of the comment (name, comment, etc.).
    """
    name = forms.CharField(label=_("Name"), max_length=50, required=False)
    email = forms.EmailField(label=_("Email address"), required=False)
    url = forms.URLField(label=_("URL"), required=False)
    comment = forms.CharField(label=_('Comment'), widget=forms.Textarea(attrs={'cols': '80', 'rows': '5'}),
                              max_length=COMMENT_MAX_LENGTH)

    def get_comment_object(self):
        """
        Return a new (unsaved) comment object based on the information in this
        form. Assumes that the form is already validated and will throw a
        ValueError if not.

        Does not set any of the fields that would come from a Request object
        (i.e. ``user`` or ``ip_address``).
        """
        if not self.is_valid():
            raise ValueError("get_comment_object may only be called on valid forms")

        CommentModel = self.get_comment_model()
        new = CommentModel(**self.get_comment_create_data())
        new = self.check_for_duplicate_comment(new)

        return new

    def get_comment_model(self):
        """
        Get the comment model to create with this form. Subclasses in custom
        comment apps should override this, get_comment_create_data, and perhaps
        check_for_duplicate_comment to provide custom comment models.
        """
        return Comment

    def get_comment_create_data(self):
        """
        Returns the dict of data to be used to create a comment. Subclasses in
        custom comment apps that override get_comment_model can override this
        method to add extra fields onto a custom comment model.
        """
        return dict(
            content_type=ContentType.objects.get_for_model(self.target_object),
            object_pk=force_text(self.target_object._get_pk_val()),
            user_name=self.cleaned_data["name"],
            comment=self.cleaned_data["comment"],
            submit_date=timezone.now(),
            site_id=settings.SITE_ID,
            is_public=True,
            is_removed=False,
        )

    def check_for_duplicate_comment(self, new):
        """
        Check that a submitted comment isn't a duplicate. This might be caused
        by someone posting a comment twice. If it is a dup, silently return the *previous* comment.
        """
        possible_duplicates = self.get_comment_model()._default_manager.using(
            self.target_object._state.db
        ).filter(
            content_type=new.content_type,
            object_pk=new.object_pk,
            user_name=new.user_name,
            user_email=new.user_email,
            user_url=new.user_url,
        )
        for old in possible_duplicates:
            if old.submit_date.date() == new.submit_date.date() and old.comment == new.comment:
                return old

        return new

    def clean_comment(self):
        """
        If COMMENTS_ALLOW_PROFANITIES is False, check that the comment doesn't
        contain anything in PROFANITIES_LIST.
        """
        comment = self.cleaned_data["comment"]
        if (not getattr(settings, 'COMMENTS_ALLOW_PROFANITIES', False) and
                getattr(settings, 'PROFANITIES_LIST', False)):
            bad_words = [w for w in settings.PROFANITIES_LIST if w in comment.lower()]
            if bad_words:
                raise forms.ValidationError(ungettext(
                    "Watch your mouth! The word %s is not allowed here.",
                    "Watch your mouth! The words %s are not allowed here.",
                    len(bad_words)) % get_text_list(
                    ['"%s%s%s"' % (i[0], '-' * (len(i) - 2), i[-1])
                     for i in bad_words], ugettext('and')))
        return comment


class CommentForm(CommentDetailsForm):
    honeypot = forms.CharField(required=False,
                               label=_('If you enter anything in this field '
                                       'your comment will be treated as spam'))
    next = forms.HiddenField();

    def clean_honeypot(self):
        """Check that nothing's been entered into the honeypot."""
        value = self.cleaned_data["honeypot"]
        if value:
            raise forms.ValidationError(self.fields["honeypot"].label)
        return value

profile/forms.py
# encoding: utf-8
from __future__ import unicode_literals

from django import forms
from django.utils.translation import ugettext_lazy as _

from userena.forms import SignupForm


class SignupFormExtra(SignupForm):
    """ 
    A form to demonstrate how to add extra fields to the signup form, in this
    case adding the first and last name.
    

    """
    first_name = forms.CharField(label=_('First name'),
                                 max_length=30,
                                 required=False)

    last_name = forms.CharField(label=_('Last name'),
                                max_length=30,
                                required=False)

    def __init__(self, *args, **kw):
        """
        
        A bit of hackery to get the first name and last name at the top of the
        form instead at the end.
        
        """
        super(SignupFormExtra, self).__init__(*args, **kw)
        # Put the first and last name at the top
        new_order = self.fields.keyOrder[:-2]
        new_order.insert(0, 'first_name')
        new_order.insert(1, 'last_name')
        self.fields.keyOrder = new_order

    def save(self):
        """ 
        Override the save method to save the first and last name to the user
        field.

        """
        # First save the parent form and get the user.
        new_user = super(SignupFormExtra, self).save()

        new_user.first_name = self.cleaned_data['first_name']
        new_user.last_name = self.cleaned_data['last_name']
        new_user.save()

        # Userena expects to get the new user from this form, so return the new
        # user.
        return new_user

templates/userena/base_userena_profile.html
{% extends 'base_general_transparentbar.html' %}
{% load i18n %}
{% load url from future %}

{% block nav %}
    <ul>
        <li><a href="/shop">
            <div>商店</div>
            <span>Lets Start</span>
        </a>
            <ul>
                <li><a href="/shop/list/">
                    <div><i class="icon-line-layout"></i>所有商品</div>
                    <span>&nbsp;</span>
                </a></li>
            </ul>
        </li>
        <li><a href="/portfolio">
            <div>项目图库</div>
            <span></span>
        </a>
        </li>
        <li><a href="/article/?t=1">
            <div>家居资讯</div>
            <span></span>
        </a>
        </li>
        <li><a href="/article/?t=2">
            <div>装修知识</div>
            <span></span>
        </a>
        </li>
        <li><a href="/about-us">
            <div>关于归梓</div>
            <span></span>
        </a>
        </li>
        <li><a href="/find-us">
            <div>找到我们</div>
            <span></span>
        </a>
        </li>
    </ul>
{% endblock %}

<!-- Start header Section-->
{% block slider %}
<section id="page-title">
    <div class="container clearfix">
        <h1>个人设置</h1>
        <ol class="breadcrumb">
            <li><a href="/">主页</a></li>
            <li class="active"><a href="/user/{{ user.username }}">个人设置</a></li>
        </ol>
    </div>
</section>
{% endblock %}
<!-- End header Section-->

{% block center-content %}
<section id="content">
    <div class="content-wrap">
        <div class="container clearfix">
            <div class="row">
                <div class="col-md-9 col-md-push-3 sep-top-2x">
                    <div class="sep-bottom-md">
                       {% block profile_content %}
                       {% endblock %}
                    </div>
                </div>
                <div class="col-md-3 col-md-pull-9 sep-top-2x">
                    <h5 class="widget-title upper sep-bottom-xs">用户帐号设置</h5>
                    <ul class="nav nav-pills nav-stacked">
                        {% block right_nav %}
                        {% endblock %}
                    </ul>
                </div>
            </div>
        </div>
    </div>
</section>
{% endblock %}

templates/userena/email_form.html
{% extends 'userena/base_userena_profile.html' %}
{% load i18n %}
{% load url from future %}

{% block content_title %}<h2 class="content-title">Account &raquo; {{ account.user.username }}</h2>{% endblock %}

{% block right_nav %}
    <li><a
            href="{% url 'userena_profile_detail' user.username %}">{% trans "View profile" %}</a>
    </li>
    <li class="cat-item"><a
            href="{% url 'userena_profile_edit' user.username %}">{% trans "Edit details" %}</a>
    </li>
    <li class="cat-item">
        <a href="{% url 'userena_password_change' user.username %}">{% trans "Change password" %}</a>
    </li>
    <li class="active"><a
            href="{% url 'userena_email_change' user.username %}">{% trans "Change email" %}</a>
    </li>
{% endblock %}

{% block profile_content %}
    <form action="" method="post">
        {% if user.username == account.user.username %}
            <ul id="nav nav-pills nav-stacked">
                <li class="first"><a
                        href="{% url 'userena_detail' user.username %}"><span>{% trans 'View profile' %}</span></a></li>
                <li><a href="{% url 'userena_edit' account.user.username %}">{% trans "Edit profile" %}</a></li>
                <li>
                    <a href="{% url 'userena_password_change' account.user.username %}">{% trans "Change password" %}</a>
                </li>
                <li class="last active"><a
                        href="{% url 'userena_email_change' account.user.username %}">{% trans "Change email" %}</a>
                </li>
            </ul>
        {% endif %}
        {% csrf_token %}
        <fieldset>
            <legend>{% trans "Change email address" %}</legend>
            <div class="form-group col-md-6">
                {{ form.as_p }}
            </div>
        </fieldset>
        <div class="col-md-4 col-md-offset-8">
            <button type="submit" class="btn btn-primary btn-xs"><i
                    class="fa fa-save"></i>&nbsp;{% trans "Change email" %}</button>
        </div>
    </form>
{% endblock %}

templates/userena/password_form.html
{% extends 'userena/base_userena_profile.html' %}
{% load i18n %}
{% load url from future %}

{% block title %}{% trans "Change password" %}{% endblock %}

{% block content_title %}<h2 class="content-title">Account &raquo; {{ account.user.username }}</h2>{% endblock %}

{% block right_nav %}
    <li><a
            href="{% url 'userena_profile_detail' user.username %}">{% trans "View profile" %}</a>
    </li>
    <li class="cat-item"><a
            href="{% url 'userena_profile_edit' user.username %}">{% trans "Edit details" %}</a>
    </li>
    <li class="active">
        <a href="{% url 'userena_password_change' user.username %}">{% trans "Change password" %}</a>
    </li>
    <li><a
            href="{% url 'userena_email_change' user.username %}">{% trans "Change email" %}</a>
    </li>
{% endblock %}

{% block profile_content %}

<form action="" method="post" id="password_change_form">
    {% if user.username == account.user.username %}
          <ul id="nav nav-pills nav-stacked">
              <li class="first"><a href="{% url 'userena_detail' user.username %}"><span>{% trans 'View profile' %}</span></a></li>
              <li><a href="{% url 'userena_edit' account.user.username %}">{% trans "Edit profile" %}</a></li>
              <li  class="active"><a href="{% url 'userena_password_change' account.user.username %}">{% trans "Change password" %}</a></li>
              <li class="last"><a href="{% url 'userena_email_change' account.user.username %}">{% trans "Change email" %}</a></li>
          </ul>
          {% endif %}
    <fieldset>
        <legend>{% trans "Change Password" %}</legend>
        {% csrf_token %}
        <div class="form-group col-md-6">
        {{ form.as_p }}
            </div>
    </fieldset>
<div class="col-md-4 col-md-offset-8">
    <button type="submit" class="btn btn-primary btn-xs"><i class="fa fa-save"></i>&nbsp;{% trans "Change password" %}</button>
    </div>
</form>
    <script type='text/javascript'>
    var editor = new Simditor({
        textarea: $('#id_content'),
        upload: {
            url: '/uploads/',
            fileKey: 'Filedata',
            params: {'csrfmiddlewaretoken': '{{ csrf_token }}'}
        }
    });

</script>
{% endblock %}

templates/userena/profile_detail.html
{% extends 'userena/base_userena_profile.html' %}
{% load i18n %}
{% load url from future %}

{% block title %}{{ profile.user.username }}'s {% trans "profile" %}.{% endblock %}
{% block content_title %}<h2 class="content-title">{{ profile.user.username }} {% if profile.user.get_full_name %}({{ profile.user.get_full_name }}){% endif %}</h2>{% endblock %}

{% block right_nav %}
    <li class="active"><a href="{% url 'userena_profile_detail' user.username %}">{% trans "View profile" %}</a>
    </li>
    <li><a href="{% url 'userena_profile_edit' user.username %}">{% trans "Edit details" %}</a>
    </li>
    <li>
        <a href="{% url 'userena_password_change' user.username %}">{% trans "Change password" %}</a>
    </li>
    <li><a  href="{% url 'userena_email_change' user.username %}">{% trans "Change email" %}</a>
    </li>
{% endblock %}

{% block profile_content %}
    <div id="details">
        <img src="{{ profile.get_mugshot_url }}" alt="{% trans "Your mugshot" %}" />
        {% if profile.user.get_full_name %}
        <p><strong>{% trans "Name" %}</strong><br /> {{ profile.user.get_full_name }}</p>
        {% endif %}
        {% if profile.age != 0 %}
        <p><strong>{% trans "Age" %}</strong><br /> {{ profile.age }}</p>
        {% endif %}
        {% if profile.website %}
        <p><strong>{% trans "Website" %}</strong><br /> <a href="{{ profile.website }}">{{ profile.website }}</a></p>
        {% endif %}
        {% if profile.location %}
        <p><strong>{% trans "Location" %}</strong><br />{{ profile.location }}</p>
        {% endif %}
        {% if profile.about_me %}
        <p><strong>{% trans "About me" %}</strong><br />{{ profile.about_me }}</p>
        {% endif %}
    </div>
{% endblock %}

templates/userena/profile_form.html
{% extends 'userena/base_userena_profile.html' %}
{% load i18n %}
{% load url from future %}

{% block title %}{% trans "Account setup" %}{% endblock %}

{% block content_title %}<h2 class="content-title">Account &raquo; {{ account.user.username }}</h2>{% endblock %}

{% block right_nav %}
    <li><a
            href="{% url 'userena_profile_detail' user.username %}">{% trans "View profile" %}</a>
    </li>
    <li class="active"><a
            href="{% url 'userena_profile_edit' user.username %}">{% trans "Edit details" %}</a>
    </li>
    <li>
        <a href="{% url 'userena_password_change' user.username %}">{% trans "Change password" %}</a>
    </li>
    <li><a
            href="{% url 'userena_email_change' user.username %}">{% trans "Change email" %}</a>
    </li>
{% endblock %}

{% block profile_content %}
    <form action="" enctype="multipart/form-data" method="post">
        {% csrf_token %}
        <fieldset>
            <h5 class="upper">编辑个人资料</h5>
            <div class="form-group col-md-6">
                <input id="id_first_name" maxlength="30" placeholder="名" name="first_name" type="text" class="form-control input-sm"/></div>
            <div class="form-group col-md-6">
                <input id="id_last_name" maxlength="30" placeholder="姓" name="last_name" type="text" class="form-control input-sm"/>
            </div>
            <div class="form-group col-md-6">
                <input id="id_mugshot" name="mugshot" type="file" class="form-control input-sm"/>
                <span class="helptext">在你的个人资料中显示的头像。</span>
            </div>
            <div class="form-group col-md-6">
                <select id="id_privacy" name="privacy" class="form-control input-sm">
                <option value="open">所有人可见</option>
                <option value="registered" selected="selected">注册用户可见</option>
                <option value="closed">任何人不可见</option>
            </select> <span class="helptext">指定谁可以浏览你的个人资料。</span></div>
            <div class="form-group col-md-6">
                <select id="id_language" name="language" class="form-control input-sm">
                <option value="zh" selected="selected">zh_CN</option>
            </select> <span class="helptext">语言设定.</span></div>
            <div class="form-group col-md-6">
                <select id="id_gender" name="gender" class="form-control input-sm">
                <option value="" selected="selected">---------</option>
                <option value="1">男性</option>
                <option value="2">女性</option>
            </select>
            </div>
            <div class="form-group col-md-6">
                <input id="id_website" maxlength="200" name="website" type="url" placeholder="个人网页" class="form-control input-sm"/>
            </div>
            <div class="form-group col-md-6">
                <input id="id_location" maxlength="255" name="location" type="text" placeholder="地址" class="form-control input-sm"/>
            </div>
            <div class="form-group col-md-6">
                <input id="id_birth_date" name="birth_date" type="text" value="{{ form.birth_date.value }}" placeholder="生日" class="form-control input-sm"/>
            </div>
            <div class="form-group col-md-8">
                <label for="id_about_me">关于我:</label> <textarea cols="40" id="id_about_me" name="about_me" rows="10" placeholder="个人说明" class="form-control input-sm">
            </textarea></div>
        </fieldset>
        <div class="col-md-4">
            <button type="submit" class="btn btn-primary btn-xs"><i
                    class="fa fa-save"></i>&nbsp;{% trans "Save changes" %}</button>
        </div>
    </form>
{% endblock %}

templates/userena/profile_list.html
{% extends 'userena/base_userena.html' %}
{% load i18n %}
{% load url from future %}

{% block content_title %}<h2 class="content-title">{% trans 'Profiles' %}</h2>{% endblock %}

{% block content %}
<ul id="account_list">
    {% for profile in profile_list %}
    <li>
        <a href="{% url 'userena_profile_detail' profile.user.username %}"><img src="{{ profile.get_mugshot_url }}" /></a>
        <a href="{% url 'userena_profile_detail' profile.user.username %}">{{ profile.user.username }}</a>
    </li>
    {% endfor %}

</ul>

{% if is_paginated %}
<div class="pagination">
    <span class="step-links">
        {% if page_obj.has_previous %}
            <a href="{% url 'userena_profile_list_paginated' page_obj.previous_page_number %}">{% trans 'previous' %}</a>
        {% endif %}

        <span class="current">
            {% trans 'Page' %} {{ page_obj.number }} {% trans 'of' %} {{ page_obj.paginator.num_pages }}.
        </span>

        {% if page_obj.has_next %}
            <a href="{% url 'userena_profile_list_paginated'  page_obj.next_page_number %}">{% trans 'next' %}</a>
        {% endif %}
    </span>
</div>
{% endif %}
{% endblock %}

templates/userena/signin_form.html
{% extends "base.html" %}

        <!-- Content
        ============================================= -->
{% block center-content %}
        <section id="content">
            <div class="content-wrap nopadding">
                <div class="section nopadding nomargin" style="width: 100%; height: 100%; position: absolute; left: 0; top: 0; background: url('/static/images/signin-bg.jpg') center center no-repeat; background-size: cover;"></div>
                <div class="section nobg full-screen nopadding nomargin">
                    <div class="container vertical-middle divcenter clearfix">
                        <div class="row center bottommargin-sm">
                            <a href="/"><img src="/static/images/logo.png" alt="回到主页" style="max-width: 50px;" title="回到主页"></a>
                        </div>
                        <div class="panel panel-default divcenter noradius noborder dark" style="max-width: 400px; background:#000;filter:alpha(opacity:70); opacity:0.7;">
                            <div class="panel-body" style="padding: 20px;">
                                <form id="login-form" class="nobottommargin" action="/user/signin/" method="POST">
                                    <h5 class="center">用户登陆</h5>
                                    {{ form.non_field_errors }}
                                    {% for field in form %}
                                        {{ field.errors }}
                                    {% endfor %}
                                    {% csrf_token %}
                                    {% if next %}<input type="hidden" name="next" value="{{ next }}" />{% endif %}
                                    <div class="form-group" id="top-login-username">
                                        <input type="text" id="id_identification" name="identification" placeholder="用户名或邮箱"
                                                       class="form-control input-small" required>
                                    </div>
                                    <div class="form-group" id="top-login-password">
                                        <input type="password" id="id_password"  name="password" placeholder="密码"
                                                       class="form-control input-small" required>
                                    </div>
                                    <div class="form-inline form-group">
                                        <div class="checkbox col-md-4 topmargin">
                                            <label>
                                                <input type="checkbox" id="id_remember_me"  name="remember_me">
                                                <small class="light"> 记住我</small>
                                            </label>
                                        </div>
                                    </div>
                                    <div class="line line-sm"></div>
                                    <div class="row form-inline form-group">
                                        <div class="col-md-6">
                                        <button type="submit" class="button button-lg button-rounded si-colored"><i class="icon-line2-user-follow"></i>
                                                    &nbsp;登录</button>
                                        </div>
                                        <div class="col-md-6">
                                            <a href="/user/signup" class="button button-rounded button button-red"><i class="icon-signin"></i><span>&nbsp;注册</span></a>
                                        </div>
                                    </div>
                                </form>
                            </div>
                        </div>

                        <div class="row center dark"><small>COPYRIGHT &copy; 归梓艺术设计.</small></div>

                    </div>
                </div>

            </div>

        </section><!-- #content end -->
{% endblock %}

templates/userena/signout.html
<!DOCTYPE html>
<html>
<head lang="en">
    <meta charset="UTF-8">
    <title></title>
</head>
<body>

</body>
</html>

templates/userena/signup_form.html
{% extends "base.html" %}

{% load i18n static %}
{% load url from future %}

<!-- Start Home Section-->
{% block center-content %}
    <section id="content">
        <div class="content-wrap nopadding">
            <div class="section nopadding nomargin"
                 style="width: 100%; height: 100%; position: absolute; left: 0; top: 0; background: url('/static/images/signup-bg.jpg') center center no-repeat; background-size: cover;"></div>
            <div class="section nobg full-screen nopadding nomargin">
                <div class="container vertical-middle divcenter clearfix">
                    <div class="row center bottommargin-sm">
                        <a href="/"><img src="/static/images/logo.png" alt="回到主页" style="max-width: 50px;" title="回到主页"></a>
                    </div>
                    <div class="panel panel-default divcenter noradius noborder dark"
                         style="max-width: 400px">
                        <div class="panel-body" style="padding: 20px;">
                            <form action="/user/signup/" method="POST">
                                {{ form.non_field_errors }}
                                    {% for field in form %}
                                        {% if field.errors %}
                                         <div class="style-msg errormsg">
                                            <div class="sb-msg"><i class="icon-remove"></i> {{ field.errors.as_text  }}</div>
                                        </div>
                                        {% endif %}
                                    {% endfor %}
                                {% csrf_token %}
                                {% if next %}<input type="hidden" name="next" value="{{ next }}" />{% endif %}
                                <div class="form-group">
                                    <input class="required form-control input" id="id_username" maxlength="30"
                                           name="username" type="text" placeholder="请输入用户名" required>
                                </div>
                                <div class="form-group">
                                    <input class="required form-control input" id="id_email" maxlength="75"
                                           name="email" type="text" placeholder="请输入邮箱" required/>
                                </div>
                                <div class="form-group">
                                    <input type="password" id="id_password1" name="password1" placeholder="请输入密码"
                                           class="required form-control input" required>
                                </div>
                                <div class="form-group">
                                    <input id="id_password2" name="password2" type="password" placeholder="请再次输入密码"
                                           class="required form-control input" required>
                                </div>
                                <div class="row form-inline form-group">
                                    <div class="col-md-4 col-md-offset-4">
                                    <button type="submit" class="button button-lg button-rounded si-colored"><i class="icon-line2-user-follow"></i>
                                                &nbsp;注册</button>
                                    </div>
                                    <div class="col-md-4">
                                        <a href="/user/signin" class="button button-rounded button button-red"><i class="icon-signin"></i><span>&nbsp;登录</span></a>
                                    </div>
                                </div>
                            </form>
                        </div>
                    </div>
                    <div class="row center dark">
                        <small>COPYRIGHT &copy; 归梓艺术设计.</small>
                    </div>

                </div>
            </div>
        </div>
    </section><!-- #content end -->
{% endblock %}